package core.controllers;

import java.util.ArrayList;

import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import core.model.DataBaseConnect;
import core.model.PasswordHasher;
import core.model.User;

/**
 * The Class LoginController.
 */
@Controller
public class LoginController {

	/** enables data base connection to users table */
	private DataBaseConnect dataBaseCon;
	
	/**
	 * Instantiates a new login controller.
	 */
	@Autowired
	public LoginController(DataBaseConnect dataBaseCon) {
		this.dataBaseCon = dataBaseCon;
	}
	
	/**
	 * Show logins the login page
	 *
	 * @param errorMsgArr the error message array, 
	 * if previous form submission was invalid, the validation errors generated by the server will be listed in this array.
	 * @return the model and view of
	 */
	@RequestMapping(value = "/login")
	public ModelAndView showLogin(@RequestParam(required = false, value = "errorMsgArr") ArrayList<String> errorMsgArr) {
		ModelAndView mv = new ModelAndView();
		mv.setViewName("login");
		if(errorMsgArr!=null) {
			mv.addObject("errorMsgArr", errorMsgArr);
		}
		return mv;
	}
	
	
	/**
	 * Called when login form is submitted, validates submission
	 * if details match then username is added to session parameter and user is redirected to home page
	 * if details dont match then error message is added to redirectAttrs and user is redirected back to login page
	 *
	 * @param username submitted
	 * @param password submitted
	 * @param current httpSession 
	 * @param redirectAttrs- stores error message array in session and passes it to login from if redirected
	 * @return the model and view
	 */
	@RequestMapping(value = "/loginAttempt")
	public ModelAndView login(@RequestParam String username,@RequestParam String password,HttpSession httpSession
			,RedirectAttributes redirectAttrs) {	 
		// tries to find user in database that has same the username 
		User user = dataBaseCon.getUser(username);
		// hashes submitted password 
		String hashedPassword  = PasswordHasher.get_SHA_512_SecurePassword(password);

		if(user != null && user.getPassword().equals(hashedPassword)) {
			httpSession.setAttribute("username", user.getUsername()); // authenticated
			ModelAndView modelAndView = new ModelAndView("redirect:/home");
			return modelAndView;
		}
		// not authenticated
		ArrayList<String> errorMsgs = new ArrayList<String>();
		errorMsgs.add("Username or password was incorrect");
		redirectAttrs.addAttribute("errorMsgArr",errorMsgs);
		ModelAndView modelAndView = new ModelAndView("redirect:/login");
		return modelAndView;
	}
	
	

	
}
